# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'drone.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import rclpy
from rclpy.node import Node
from rclpy.qos import DurabilityPolicy, HistoryPolicy, QoSProfile

from sensor_msgs.msg import Image
from std_msgs.msg import Int16, String
import math
import numpy as np
import time
import random 

import cv2

import cv2
from cv_bridge import CvBridge


import numpy as np
import cv2

from PyQt5 import *
from PyQt5.QtCore import QTimer
from PyQt5 import QtGui
from PyQt5.QtWidgets import *
from PyQt5.QtWidgets import QWidget, QApplication, QLabel, QVBoxLayout
from PyQt5.QtGui import QPixmap
import sys
import cv2
from PyQt5.QtCore import pyqtSignal, pyqtSlot, Qt, QThread
import numpy as np

strats = [[0,1,2],[0,2,1],[1,0,2],[1,2,0],[2,0,1],[2,1,0]]

class Ui_View(QWidget):
    def __init__(self):
        super().__init__()
        self.disply_width = 791
        self.display_height = 480

        
        self.br = CvBridge()

        # create the video capture thread
        self.timer = QTimer(self)
        self.timer.timeout.connect(self.update)
        self.timer.start(5)

        self.runs = 1
        self.succ = 0
        self.stra = [0,0,0,0,0,0]


        rclpy.init(args=None)

        self.sub_Node = Node('Score')
        self.sta = self.sub_Node.create_subscription(
            String, '/status',self.status_callback, 10)
        self.button_publisher = self.sub_Node.create_publisher(Int16, '/hidder', 10)
        
        self.sub2 = self.sub_Node.create_subscription(
            String, '/score',self.score_callback, 10)


    def update(self):
        rclpy.spin_once(self.sub_Node)
        self.successes.setText(str(self.succ))
        self.totalRuns.setText(str(self.runs))


    def status_callback(self, msgs):
        text = msgs.data
        self.statusLabel.setText(text)

    def score_callback(self, msg):
        score = msg.data
        score = score.split(',')
        self.stra = score[:6]
        self.runs = score[9]
        self.succ = score[10]

        _translate = QtCore.QCoreApplication.translate
        for i in range(len(self.stra)):
            item = self.spotList.item(i)
            item.setText(_translate("View", f'{strats[i][0]}->{strats[i][1]}->{strats[i][2]}  used {self.stra[i]}'))



    def closeEvent(self, event):
        self.thread.stop()
        event.accept()

    def clicked1(self):
        msg = Int16()
        msg.data = 0
        self.button_publisher.publish(msg)
    
    def clicked2(self):
        msg = Int16()
        msg.data = 1
        self.button_publisher.publish(msg)

    def clicked3(self):
        msg = Int16()
        msg.data = 2
        self.button_publisher.publish(msg)
    




    def setupUi(self, View):
        View.setObjectName("View")
        View.resize(781, 764)
        self.centralwidget = QtWidgets.QWidget(View)
        self.centralwidget.setObjectName("centralwidget")
        self.image_label = QtWidgets.QLabel(self.centralwidget)
        self.image_label.setGeometry(QtCore.QRect(0, 0, 791, 371))
        self.image_label.setObjectName("image_label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(0, 430, 221, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.clicked1)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(280, 430, 221, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.clicked2)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(560, 430, 221, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.clicked3)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 390, 66, 19))
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 370, 791, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.statusLabel = QtWidgets.QLabel(self.centralwidget)
        self.statusLabel.setGeometry(QtCore.QRect(80, 390, 371, 19))
        self.statusLabel.setObjectName("statusLabel")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 520, 81, 19))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(0, 500, 121, 19))
        self.label_4.setObjectName("label_4")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(0, 480, 781, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(505, 500, 141, 20))
        self.label_5.setObjectName("label_5")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(480, 490, 20, 241))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.totalRuns = QtWidgets.QLabel(self.centralwidget)
        self.totalRuns.setGeometry(QtCore.QRect(150, 500, 66, 19))
        self.totalRuns.setObjectName("totalRuns")
        self.successes = QtWidgets.QLabel(self.centralwidget)
        self.successes.setGeometry(QtCore.QRect(150, 520, 66, 19))
        self.successes.setObjectName("successes")
        self.spotList = QtWidgets.QListWidget(self.centralwidget)
        self.spotList.setGeometry(QtCore.QRect(650, 490, 121, 211))
        self.spotList.setObjectName("spotList")
        item = QtWidgets.QListWidgetItem()
        self.spotList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.spotList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.spotList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.spotList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.spotList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.spotList.addItem(item)
        View.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(View)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 781, 24))
        self.menubar.setObjectName("menubar")
        View.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(View)
        self.statusbar.setObjectName("statusbar")
        View.setStatusBar(self.statusbar)

        image = cv2.imread("Dep.png")
        rgb_image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        h, w, ch = rgb_image.shape
        bytes_per_line = ch * w
        convert_to_Qt_format = QtGui.QImage(rgb_image.data, w, h, bytes_per_line, QtGui.QImage.Format_RGB888)
        p = convert_to_Qt_format.scaled(self.disply_width, self.display_height, Qt.KeepAspectRatio)
        p = QPixmap.fromImage(p)


        #pixmap = QPixmap("Dep.png") 
        self.image_label.setPixmap(p) 

        self.retranslateUi(View)
        QtCore.QMetaObject.connectSlotsByName(View)

    def retranslateUi(self, View):
        _translate = QtCore.QCoreApplication.translate
        View.setWindowTitle(_translate("View", "Human Search Trial"))
        self.pushButton.setText(_translate("View", "Spot 1"))
        self.pushButton_2.setText(_translate("View", "Spot 2"))
        self.pushButton_3.setText(_translate("View", "Spot 3"))
        self.label.setText(_translate("View", "Status:"))
        self.statusLabel.setText(_translate("View", "Waiting for your first selection"))
        self.label_3.setText(_translate("View", "Detections:"))
        self.label_4.setText(_translate("View", "Amount of Runs"))
        self.label_5.setText(_translate("View", "Used Strategies:"))
        self.totalRuns.setText(_translate("View", "TextLabel"))
        self.successes.setText(_translate("View", "TextLabel"))
        __sortingEnabled = self.spotList.isSortingEnabled()
        self.spotList.setSortingEnabled(False)


        for i in range(len(self.stra)):
            item = self.spotList.item(i)
            item.setText(_translate("View", f'{strats[i][0]}->{strats[i][1]}->{strats[i][2]}  used x{self.stra[i]}'))
        self.spotList.setSortingEnabled(__sortingEnabled)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    View = QtWidgets.QMainWindow()
    ui = Ui_View()
    ui.setupUi(View)
    View.show()
    sys.exit(app.exec_())
